workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == "push"
    - if: $CI_PIPELINE_SOURCE == "web"
    - when: never

stages:
  - analyse
  - test
  - build
  - release

image: python:3.9

pre-commit:
  stage: analyse
  before_script:
    - set -x
    - echo $PWD
    - pip install poetry
    - poetry install
  script:
    - poetry run pre-commit run --all-files --color=always
  cache:
    key: pre-commit
    paths:
      - ~/.cache/pre-commit

.test: &test
  stage: test
  before_script:
    - pip install poetry
    - poetry install
  script:
    - poetry run py.test

test-python3.7:
  image: python:3.7
  <<: *test

test-python3.8:
  image: python:3.8
  <<: *test

test-python3.9:
  image: python:3.9
  <<: *test

build:
  stage: build
  before_script:
    - pip install poetry
    - poetry install
  script:
    - poetry build
  artifacts:
    paths:
      - dist/
    expire_in: 30 days
  rules:
    - if: $CI_COMMIT_TAG

release:
  stage: release
  dependencies:
    - build
  before_script:
    - pip install poetry
  script:
    - echo $PYPI_USERNAME
    - poetry publish -u $PYPI_USERNAME -p $PYPI_PASSWORD
  rules:
    - if: $CI_COMMIT_TAG
